---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/tailscale-cluster
  # Tailscale Ingress (HTTPS with automatic certs)
  - ingress-monitoring.yaml

labels:
  - pairs:
      app.kubernetes.io/instance: shangkuei-lab
      app.kubernetes.io/environment: lab
