---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/tailscale-cluster
  # Tailscale-exposed services
  - service-prometheus-tailscale.yaml
  - service-loki-tailscale.yaml

labels:
  - pairs:
      app.kubernetes.io/instance: shangkuei-lab
      app.kubernetes.io/environment: lab
