#ENC[AES256_GCM,data:eI0b3kPtrSuSxeLfWYF3rj6iYkw48drvjr8Gwvfeg80v5qk+PEiEXrS++jdDKZl1YQQArTsIAb2BtNH/,iv:bSRG0RN+WvOKZEAEbu53k6kS6l+QrpyaKzTe5RYPsoY=,tag:9Xp/tdPfT/A6RneJfJfXQQ==,type:comment]
#ENC[AES256_GCM,data:83eyN6cqZYwhnNahx0aMKvV6NNfadz8iMy/CuhbNjsDahIvbtX93umNpn542bRlQj/KCJw==,iv:4wYlkZSiLv393IDqIaVhCy1uMZHwoqJ0Jq7PhTDQ+E0=,tag:ig5rstO3hF7UxsInvdjL3A==,type:comment]
#
#ENC[AES256_GCM,data:gI07ZoRromg73p7ph4v2qXv1M/1DzxAzz2x9T7CMeVIxCMrfZvywjvCUiBn/9kaAQflQUrPHSYufbFWoYg==,iv:MZCcTX6RuKEX5n39vQMxIF81aB08/91+0HCtZC/ujHM=,tag:cTDZZ6V5nd9E0t3I4nV7yg==,type:comment]
services:
    tailscale:
        image: ENC[AES256_GCM,data:FIHJGs2B85PFG1fl38N1dApY45xq2dfQtVo=,iv:62dgAunQGoxvRYW1wYuggm5wvtttkT+Im3QUv+M/Au4=,tag:njr8qIvBIhXpQUQeD26u5w==,type:str]
        container_name: ENC[AES256_GCM,data:nGjPX0u63Yyl6f0kKvmr9hupHySk,iv:4qN2RxOOCovY07/kaCyMEMC80JNcDWSDusKqgmoYdxY=,tag:7JWQv3w/mH/g7zKYGnLZ9w==,type:str]
        hostname: ENC[AES256_GCM,data:WhqiQt3Vh1JPFC8=,iv:TBeahy/CZ8vvNu/whYz34ESWL+LLHmfLHCUotL8a4RA=,tag:MOamFHfIwM0oCBJ6p2W0JA==,type:str]
        restart: ENC[AES256_GCM,data:KufZXXvFCkmUQM6N8eA=,iv:LO8G798SK6NYunLM8lrQT5jf12ezZTZy657O01/gbAI=,tag:f82Bwu6hTPF6bx79ftIwLg==,type:str]
        cap_add:
            - ENC[AES256_GCM,data:UCs44FijYeZS,iv:BlLAXHw2wOV7GsVBo7/cVCZRoA59ux1TErzzOVrMt0Q=,tag:fz0PyJ4bXg6vsYX/TEZqDQ==,type:str]
        environment:
            - ENC[AES256_GCM,data:xLfuat1CQEMvYHs+rifqqGDVCA6S+IZdcC0=,iv:y95cd6M0XIiqnWktjLLauXMTiNpYup7PjhQ8Yn0JwJc=,tag:hXERhUhWArZRvTVFRVDTwg==,type:str]
            - ENC[AES256_GCM,data:4mtBb5N/2dRhR9iFF4GXW1XmdJ3UyR210qJ+dODVXg==,iv:N85hE41gap2ESNRZ2OuUtri1U6dLrg4SSTgP2rwFa80=,tag:pHbolduauS6mFk+VAfmqgw==,type:str]
            - ENC[AES256_GCM,data:prpYDQoPb14kSpB/adfvJMAd,iv:rZrqck0KJRZZSaSbbepf+ZXUc4ecAtAOYmBbSLc6QR0=,tag:ZtZaJX+lsKRlAnoCLRYeXQ==,type:str]
            - ENC[AES256_GCM,data:CVbgF5JoUDUC9VqszOpr4Oin,iv:zPF6CeqzW+1ZGCN54fbUMKItfDuAGGa7dS25295Alhk=,tag:8dWgMNNGHoEPUHaE5V1hzg==,type:str]
            - ENC[AES256_GCM,data:ONnmFNp1aPVuB4AKzF/FnJAfdH1EAm43rFuBYC4oWUw=,iv:QqZQALO8izM1Y/mjij2znJJOIH8HorCXYHgt/T8sggY=,tag:bqMbX8zSbf+4eBnfKYWL0w==,type:str]
        volumes:
            - ENC[AES256_GCM,data:dtm3k5w7TcF239pKStNHirNoN/wQv5AG/KU1E/i4LkOvWe2JNpoQnHN4/dVQIHPMNuWMLBiMSU+uiA==,iv:cBcXZm+KHboLz7ZPGKr6Ed3p5VcHghcSamp7dsCevh0=,tag:pG6lNh6pVmk0TwX11kNzxQ==,type:str]
        devices:
            - ENC[AES256_GCM,data:RArUoKaUEctbC4aKOFsjQAARQVfeu9mUAQ==,iv:RpjdmyLN0pnj7qthywiypY0i4jGnzGvJRkdoy+23ALk=,tag:CVC06awSvyva1qysR/MHfQ==,type:str]
        networks:
            alloy:
                ipv4_address: ENC[AES256_GCM,data:Q9K8qX9wSAA79Po=,iv:k78ihZMs1C3EWcYpoyfnBkJl0PnQqrGfVuC80Sowq/I=,tag:ftChqFf6BS5DjkBJMIUUxg==,type:str]
            cloudflared: null
    cloudflared:
        depends_on:
            - ENC[AES256_GCM,data:sxOvYeP9qpOR,iv:iayliQi1hmOTsDMkEbTXkwlsKSTf8zDOEyloLHF1gT4=,tag:7PTII5izdtUB8LmqodqJeQ==,type:str]
        network_mode: ENC[AES256_GCM,data:/FyMYc3KixTTSEl3eBtBw90=,iv:atB0NbEvifHD4pIolbO0vDEbEU0RprAmk04f2pLXsWw=,tag:6wTix1n1cAxZPdinwZLt1A==,type:str]
networks:
    alloy:
        external: ENC[AES256_GCM,data:s9FdgQ==,iv:+L9DP1nadBR2q3P3q98RML16OamsuzA+OEU8ZO7p/qk=,tag:wNHqHte4kL5CHeu1MVjH7A==,type:bool]
        name: ENC[AES256_GCM,data:OHkZYdZzVsMIU3nNKLs=,iv:H0aXEgeo/T/+nfEtFnUwn893RkuXfp9csN15qhjKH2w=,tag:SrFR9EhyRM7kfzYaSrYDHQ==,type:str]
sops:
    age:
        - recipient: age18pns8av0m2g3wgenjnfkj046340azfytlp0jgpkw4dw7zkh83dwqlct4np
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1aDJqbVlRUUd0cy84UytI
            WHRBM3ZSZUNxZnU3dnd0MDB1M2poWUxMNWtRCmJZRFFVaHlOTmNkdnNSNTh6SUw3
            VmRpd3VYZDBROTRRaXJ3Q212bERuejgKLS0tIDE4QU1OUWxTQTY5R1ZYb0pTblp4
            bFBwbVdLNWF2QmNEWmRiN1RpaXpNejgKttypDSSsXq8QstF0gJBUUDA1dwSM9Voy
            bH0wK4EBplcDm0UyVfZKG+BLRs9HHAKk9grgFkhamttizXzrBEejEQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T14:23:49Z"
    mac: ENC[AES256_GCM,data:WZV6tmk6rCkUqo/GqkKyw+1TJvMoYpR9PsaoZj8vafa72d0tITB7ucCfI1HtFLJhXUZVK1UgBHAH0KJU1Luw3LaDzziPuGyVewI3TlAZ+fqNgm/NK63Sxwj1JSul+yPYZCeP19SPTnFqyG/ul8WAHI8gTeCZp4LQEW4A/0b1MVo=,iv:Juo40F5ed2tl5ZROz1fpKcdRQQ9ZYil10fbqg8fY6nI=,tag:s77kgUpa14gY/3gXb1tWBQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
