---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Namespace not needed - using kube-system
  # - namespace-openebs.yaml
  - helmrepository-openebs.yaml
  - helmrelease-openebs.yaml

labels:
  - pairs:
      app.kubernetes.io/name: openebs
      app.kubernetes.io/managed-by: flux
