---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# goldilocks GitOps resources
# Dashboard and controller for VPA recommendations

resources:
  - namespace-goldilocks.yaml
  - helmrelease-goldilocks.yaml

labels:
  - pairs:
      app.kubernetes.io/name: goldilocks
      app.kubernetes.io/managed-by: flux
