---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# ArgoCD Operator installed via Helm
# Manages ArgoCD installations via ArgoCD CRDs
# Source: https://github.com/argoproj-labs/argocd-operator

resources:
  - namespace-argocd.yaml
  - helmrepository-argocd-operator.yaml
  - helmrelease-argocd-operator.yaml

labels:
  - pairs:
      app.kubernetes.io/name: argocd-operator
      app.kubernetes.io/managed-by: helm
