---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd-test-app1

resources:
  - ../../base

# KSOPS generator for decrypting SOPS secrets
generators:
  - ksops-generator.yaml

labels:
  - pairs:
      app.kubernetes.io/instance: shangkuei-xyz-talos
      app.kubernetes.io/environment: test
