#ENC[AES256_GCM,data:zw/ZtRZ4N8191u48Fo3DbVVedEEmORJhSQsEIqFbkZQ8XVLR2wYWWI2IxbI1Ri+o,iv:J7qsn6ASllAgn4PmtqcC/0+ySG/9JQjKJcZ5mkhohEA=,tag:BKQrd2Mu9DBDn8Onz+Eiig==,type:comment]
#ENC[AES256_GCM,data:mY3Y24KcygSbhjWCT8+byWGhBdWBUTRMjSLFoQQGptoDXDlI8zvrGSeSBQlVpZEc2V/qLJmJddIo3u8Xjw9YfAfczJeXxE4vI1Vn,iv:BwpQqHFDardBu0RQd9giyuWe3bOFMJj3qaw/oU8qLaM=,tag:HJARMtZ/dRTPuxOCRkfF+w==,type:comment]
#
#ENC[AES256_GCM,data:FRCWhK/qK36Hn8E7wfgzqHDfLPies1ZpnCIdcinKgMQuNdmbxMT2Vx8GIt+HKxsFAEhNa10=,iv:7agU3O5C43Llb8SWzSW8HS2nGpSM/DO909rBLXsv5ho=,tag:qNTBM8Py1N+B5YOM8vLfhw==,type:comment]
#ENC[AES256_GCM,data:6YWrBoT0cEqahppN5/NaTuvlj/4p2waLHzo4E34PfN5JJeJchaxQDLA2LbhEOaA146pqxqjyT0Az8+iAbgZFBVQ=,iv:M21frb2gVzH/zGS76JhkMELtGj9AQzNSf2eWvjuSEfc=,tag:wdCV/RT158e9pCyxKxsgCQ==,type:comment]
services:
    tailscale:
        image: ENC[AES256_GCM,data:W7xcs2cCMTXqmknFoLG6QbPA8a0FskEQM/U=,iv:K5EbZiFelOfx5Kr+fZ7K/8F7U/yOn/4OFT0MHS4HmX8=,tag:bfU7JB7U/y4CjS2F9NOP5Q==,type:str]
        container_name: ENC[AES256_GCM,data:YIZQRAIshuaZOw0ZMrBWh54shTd2,iv:ItH53kBqV6tqjlgY80kFZqmw2nzPkYtDbMs0sz/QicI=,tag:LUVjnlKb8yGWjhWJ/nrXBA==,type:str]
        hostname: ENC[AES256_GCM,data:a4z3x3JS7SEVooE=,iv:tEoqGbwLEBYgA4dovrT5B2NnX0RlDYFfll1u/+9ETqQ=,tag:xhbW4aayVOHWgr8EguMGIA==,type:str]
        restart: ENC[AES256_GCM,data:0YpJkNcYYH0sOfPZ9/s=,iv:rOtXDAKcdiA0FTQqqDahXJSiJjFyQrseulIPM7hPz+Q=,tag:IEmaZfSK0u2ZshBWBi2HNw==,type:str]
        cap_add:
            - ENC[AES256_GCM,data:Az9YgaMqmljg,iv:/XaQC3wDmI8KANGOxyRVNgF0lGFGy7+SD64C4ptE928=,tag:MIu3BzpnT9cFI4adq58j3A==,type:str]
        environment:
            - ENC[AES256_GCM,data:BPcPjv8oFt9tHOQf0+bgfA3TExEDHTBlSNAw8q0clpqGbNKi/XU=,iv:qz8JfJhsSf/wl4aQZXbndHOFLS7vzoBcaDwQSiA6+E4=,tag:mPtqgGF/Z9qaGgZpi5PJjg==,type:comment]
            - ENC[AES256_GCM,data:d1sR4Z7wMo4qUIRs4gUR3Mv7hah0yRNt,iv:npSNhul/Iz/B87j9l2lrsVDHA0czW24ll8lGQcNZzvE=,tag:WZviDjbrycGdTCBds39I7A==,type:str]
            - ENC[AES256_GCM,data:0tLcCI2Jq2AElKi/68eslaBSTTOIlsTCGtP2cw==,iv:orqI69P1tahRv2Zsw+2ryGswZKRTTcbFr9qgf8dcdeQ=,tag:Fj/PvR86IWGyMqDJPnGdZQ==,type:comment]
            - ENC[AES256_GCM,data:eBgYZLRHACjDn2C2bGzE8S5cKvM4RTgcRPxd0LliF/0=,iv:dGssfmGTkInJNHsjPfkxhAB5yrkJSuIUtaVi+5iW2Yc=,tag:3vWjxCA4PQHBkZrCHmcBAQ==,type:str]
            - ENC[AES256_GCM,data:LwEjyOQI42HMjMWWJQO8ykJW4otA0NYxkg==,iv:17QSUxhxPTV+TgskbpRfBzjMROKhbELaoDDrForN4Tc=,tag:2b1Qm3AxYCx+Thembu7IBA==,type:comment]
            - ENC[AES256_GCM,data:vdzvX6kWWW+QVQ6xrOzjn85nNGvPVZcOSEJvT98744NsEQ==,iv:exAW3lU+qZnopy7jDPDabTusXCCa91q6QbFmKxsElqI=,tag:MMWVsYH38aMys32ilsRl7g==,type:str]
            - ENC[AES256_GCM,data:bRePO7Ag7pukykF4+XbXfvO9KAKW9nBW5Q15rEqM,iv:rupbJnvvvVlFikHMSgeaznGz8tWBz9nEEL+XOd5cVWw=,tag:2wvYjQ07RaL/92huh75bOg==,type:comment]
            - ENC[AES256_GCM,data:+kPUVcIkcLOIXTFNR0eLaAmhMqlMnGYpHvkJigLY4A==,iv:WYVMjNSDLRn8a6BSGeRdhvarUp7pqlCU9Lb65g59V1A=,tag:gO3g1sgviy/GmNOr+qjS8Q==,type:str]
            - ENC[AES256_GCM,data:4+n2wDarRLBInNPOmco/fmh3zU43RAtoDAxP8g6T8GRw,iv:BnEfYglFR7Esqt00IigfjVEN4Z6vpyFInLQWnI+quRI=,tag:mmJ7LriSaG44NfPKfTMmig==,type:comment]
            - ENC[AES256_GCM,data:7EWgO85JVkataORvPpLxk74e,iv:CJpef7wmz5wDCWmPd/2b48K99STAO/vi3ePEVxkCyHM=,tag:sR3DnqdqKCodulj/ecbsBw==,type:str]
        volumes:
            - ENC[AES256_GCM,data:Beh/6/V1hjbD4mHegdI0hlH7XbnG5tIcle8=,iv:WDUlwJD1OXwVutI8p5CNS+oUaBtO6dn0g2LSdK+juXc=,tag:fS2M7jtLGOJYiqYRU1fjDA==,type:comment]
            - ENC[AES256_GCM,data:EBGlroDLL8Ob6/yL7zy7RMp2nIKwgQX9E4TLOk+VXCRACytOEA4Skh71Pt+tm5q/eGYcq2LuHNhM7g==,iv:rph4pYOk2elbLzOpcFuJOuhgkyj8L0uoWqsiOTWdLmg=,tag:5BAYYaQOKK+EW9fP7XvPBg==,type:str]
            - ENC[AES256_GCM,data:s1CxNgs+Pxi71OjDUL6vvNyvvmI=,iv:Rar9bAJzMoiF28qQXBB8Nrc/DLMfAcC80+xkp0tIvXI=,tag:5uwaYinxV+WoEEyUI/yFCw==,type:comment]
            - ENC[AES256_GCM,data:KRnW2OQxyKZUgLRliLXv2WHpSgt4CfK11BgOBOoDskTaVpqManGJ4RwByQfX+4yTLzi3uOMlICzopB7OXJR+WDKNMT0aKZp+VnaRi5wcwr0Jtw==,iv:7V2VOZRb/tNDGeuH3EE5qHKaRW/OT2Q5pKQ5FPP2Bng=,tag:vvyOcjdnps/adKLjSgHseg==,type:str]
        devices:
            - ENC[AES256_GCM,data:gFH71dlD4PIhmO0n1l15+hldnfjt0AFr7g==,iv:n6MoGfcBoO95UFBZKLaZcBBNCHq8un/yNmy/irtnUzw=,tag:bnkaF1ESMEvDcUG4GllYdQ==,type:str]
        networks:
            - ENC[AES256_GCM,data:8gjtbWq9j7DcG38=,iv:UsxXPmrAL/Zyu6hiIbbnOWzQK4oBUk0rGseLqpjQj+w=,tag:/W7SXMd45Y9emmDhw+9Tvw==,type:str]
    vaultwarden:
        #ENC[AES256_GCM,data:jLgrzK5KLyWHy7M+d01PRlR3kRLEZjWTyTDT8X2S,iv:fInM5K2MnHq8HIi2EccmQYXoT2wqT2NYY8LLl7tFz6I=,tag:Sja1zJh74zH9oQ615pmUzg==,type:comment]
        network_mode: ENC[AES256_GCM,data:d96TkRhEAG60weMdXG6eN1I=,iv:G2bBxkop6MBtOcRoob6v7MzZC85E+Ny1Ri1X9yF4mPs=,tag:/WmTGcSwLGvEI110e+FBkA==,type:str]
        depends_on:
            - ENC[AES256_GCM,data:aEx7UNrYHm80,iv:c+lt5z4UHlorkhyjoWRf34H4dDcm2j4XXiR8jdO50+I=,tag:XABYuavziZJCpFzqqPhkSg==,type:str]
    database:
        networks:
            - ENC[AES256_GCM,data:PRHwjoqJszYsWcc=,iv:cvfT9Fd7HTMwARNhZSuktLGWTQTSljfpwa9zC2cRZy4=,tag:juIbbesACUyovE7eP/G0dA==,type:str]
sops:
    age:
        - recipient: age18pns8av0m2g3wgenjnfkj046340azfytlp0jgpkw4dw7zkh83dwqlct4np
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJNDJWYW9YRWZtS0diTWJ2
            ZFpTS2hFS0JlakhzOHQ4cUZnOTlSMDIveVdjCkhKbVU1OWNMT0QyVkFWeUlCMUlW
            OWQ5VWJwcUJsbUxPTzV3cTRqSHBIL0UKLS0tIDlaMEJHaEhVQm1pajM4d1diQ0Vs
            OGd5ekp5MjRJU0tFcHVQV0R4MkluZkkKIeP9FlxpImwyOW//fbqfW0sy3un0ViL2
            E7eJw0hqqce01K4PvDp4SqPiWGnI+UONqWHx9sVyFRtcvSd+tbFxPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-28T06:06:43Z"
    mac: ENC[AES256_GCM,data:XF+TLjIk0J0LGkgBGACpNMu4McbQh0GITP5BvZ8V3Kl7B3zzmWUPntriFXV4H9ca7QWWYEVFS2POgjYFV6PvPT967X2oneSWc7X+DANkXoL2cagTtJLzYOJpf57nad1eJMv8CCjp3GIPhcjkGnfw2J/1fpCrh6yMts5LZO7Qlsk=,iv:rJzahgU3ck3GWUCttjOgXnt4eoTb1qXQ4TURtcVQC9w=,tag:IcC7GqaWlEq7Omn9nciGOA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
