# Flux Git credentials secret (ENCRYPTED)
# Managed by Terraform: kubernetes_secret.flux_git_credentials
# Only stringData section is encrypted (metadata, kind, apiVersion are plaintext)
apiVersion: v1
kind: Secret
metadata:
    name: flux-system
    namespace: flux-system
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:l8z7,iv:Y5R9D+/FJoo5ZgyOxEiXFuWpd87IsMTpwQJCbpZ7EB8=,tag:AweKwjqh6vC2qDz/iPGxWg==,type:str]
    password: ENC[AES256_GCM,data:cNk5G58/joXICMy0iW9pc0wnHxp0xbFedEpp2vE3UhpjVWpdFnF0og==,iv:YIAEaR10E96dl5YxgUlFuaP5Rqe0pfTzhiabDxVEqWQ=,tag:8gNiXf4wR2SkZv/8VnBpdA==,type:str]
sops:
    age:
        - recipient: age1xd9vrcj6n5nazq3tek8t89qxaky5eg9339phyddeemu99hqgvfcqkr2ysp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1dDNsSWY1RXc4bW1QYXh1
            TkpldVBiaWFaZnExTXAwakR4TEpzRkVpakU0CjUrUXp4ejFyVHZlWkRCTVVsVTJi
            ckY0KzlNZFQrV2hWdi9lY3Z5WmpOYkUKLS0tIHJoTXp4OGphenBELzc4L3FzaUFN
            UlQzT1RtamlzeHZLZThGTDhGbXNWV1UKnDhuqssF6gFSgxbNugeb6eRaTGwHDRKa
            oq6dH5BTmFIh2ejBv0Yji197mO4z+8zvX/TDZIDrszmvdMAoR1Nhlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-14T05:42:43Z"
    mac: ENC[AES256_GCM,data:6o6V7H3gWrqAFN0HrQiicNWNQtbevgaUsa5nCn5YXasFsU40jngqLVUTlIKWsdTM6QgmBKzLwmIVovE/sn18vaGQfDgk6YcBzbxfs61mNCg0n8HiQwwu2Mvh/gpnDKoxWlcIwQuNDLAU86iGVlCtY4SPDK5MDXQwOeZg5nrvmNM=,iv:cN57dupQfKEmV+G3t17QlJQTji++jnayJ3YqvAeBkuA=,tag:7uwaEJS4cU/Cu0BR/dNbOA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
