# SOPS age encryption key secret (ENCRYPTED)
# Managed by Terraform: kubernetes_secret.sops_age
# Only stringData section is encrypted (metadata, kind, apiVersion are plaintext)
apiVersion: v1
kind: Secret
metadata:
    name: sops-age
    namespace: flux-system
type: Opaque
stringData:
    age.agekey: ENC[AES256_GCM,data:trPvBug0pzQMLxd8KzyHz8SjRGkl8Zj8v1iX+XqLyAq42hGgki8KdIpQFPblHqGmz5Pomx9ePwcMBBwZgL6QOkR2P4RIcJuZ6P1NknMMk5S3HgBBzTCqdY6ly3fxdqdFYhhvL4Cpifd1SycAqyzXNG3uvV1A5GpMzew1Z8CyrGvUt54WEUdZT+a6kZZLdtvK9wNmcXh9bsQnJVG+eTsBiUYmPtdfNd1i5otzO/rNNWhHpl3I/g0yeDED8d1Z,iv:iFoKcn7MHQ3tWraJb5Cfh/k1V/MuRUy7fUD/OEmM3Fs=,tag:7edxxj5HANNwOTfnPrqZ9A==,type:str]
sops:
    age:
        - recipient: age1xd9vrcj6n5nazq3tek8t89qxaky5eg9339phyddeemu99hqgvfcqkr2ysp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPZ21qVDYwN3VzVmcvbzdl
            L1ZwQUg0SDN3TDd6VUY2dzdsVDVDOUZUcW1jCkJEU1FzMmVpVDhUNWVhdXdDL2pm
            bHNhbVNBdVF5Q21wblkvZjVZdVdnWG8KLS0tIGpZSlBEbTNvMHRMZkpKZ3ZOUEdj
            a1lLV0UrcHJ4dG5ZZDZsVzJqb0dsbmcKBhBu5U14EqSnGe/fCHbL+Ldzg96b9+Y8
            0gIbXap05omr4rtpGqrTkx4RHqWpbVbF9lDxLXuS+XjiEe/ka+DBnQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-13T13:31:17Z"
    mac: ENC[AES256_GCM,data:x/ypvAZbtu2nwPOxAZwGKdzZZupL99/R5yqQLo2gveh+lSGARaMbnqEOxUBjzoNVT0EW5umEqWBex/KgAFlHhtdgTDNs3Lud4RhsZPBLyATOdIWM13m2Vm3Gce4AZJv0kvPkhYF7+LyE0Mt/0WTmbCSBZtG7nxOV0cXZJLxaexE=,iv:MqZVhnBxXbNIefHWNyAu2Qyp86qq6bn/VgsDFa14LBw=,tag:WB0RE9gtDSMVBO5MLLWsQA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
