---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - app1.yaml
  - app2.yaml

labels:
  - pairs:
      app.kubernetes.io/managed-by: argocd
      app.kubernetes.io/component: application
