---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# kubelet-serving-cert-approver GitOps resources
# GitRepository: Upstream artifact source (v0.10.1)
# ArtifactGenerator: Extracts standalone-install.yaml as ExternalArtifact

resources:
  - gitrepository-kubelet-serving-cert-approver.yaml
  - artifactgenerator-kubelet-serving-cert-approver.yaml

labels:
  - pairs:
      app.kubernetes.io/name: kubelet-serving-cert-approver
      app.kubernetes.io/managed-by: flux
