---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace-monitoring.yaml
  - helmrepository-prometheus-community.yaml
  - helmrelease-kube-prometheus-stack.yaml

labels:
  - pairs:
      app.kubernetes.io/name: kube-prometheus-stack
      app.kubernetes.io/managed-by: flux
