# Tailscale OAuth credentials secret (ENCRYPTED)
# Expected by tailscale-operator chart when oauth values are not set
# Keys must be 'client_id' and 'client_secret' (underscores, not camelCase)
apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: tailscale
type: Opaque
stringData:
    client_id: ENC[AES256_GCM,data:Xa4SnvCH3ys6MQIrCzpyT8I=,iv:AprWt+Tl3Dj9pqF/47Y5+tVBH2BCz6dEuSdJuBTs9Js=,tag:ysu8nU9z8HPUKFWBrMi7tQ==,type:str]
    client_secret: ENC[AES256_GCM,data:yxglzuBbyswLLkayLmIjUyoJsVFXBf+UprUyIMEciVXUdnyZHxVJsfcUrIj2Fwecl/vm2xq7+bPX8shXEVf8tA==,iv:xpgLAH1/fswEmN8U5WWk7bNVXI1gPiB5RK3pDIZ0nwI=,tag:dhkTRdb555CjHc7A0w+JWQ==,type:str]
sops:
    age:
        - recipient: age169cuuq59c5dzagy3j70h7ul0q5meeqvmdc84vx4ffwg6ptxsgdvshem39p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLWGpDYVBIcmQyeWJVSzZ2
            eUs4UVVLYmtRS2xUOU4rYUgrQUtSSkZ6MG1BCmNyZlFZU09QNzlKQkRDQk4yMjBY
            SW5nSngyVWZuVVppQW0zaUROcDdraGcKLS0tIG93Y05QOGIvNXRNL0l3cUJHaVVR
            dUdCTElSVkdTOEE1Z0lzR2ZsYlhZRDQKF1S+biQeaPTEbelWIZ+3GlXCOJxF7ifB
            613jiH61ghPGLW5tZMuokWvOOZiInwO2jnfTsFWC7M/5eRKAs8dFyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-18T13:15:40Z"
    mac: ENC[AES256_GCM,data:8qoJQ8HHZe4ws6ZHzC2XqZhpLT2OVzHPJdtHvopMPhLpJy3djy63AoryISwEknjyWr5rfaMtWDAud+djjSE4kwwoDb272X9LMn5MPGcOcItZSAv9uzp2Dt7tfOaZnhFD73PDIQ/mAEs5gseEZicIxsPzl26RtYdBaBBY7rN17s0=,iv:ts5rLJfU4Rqc88BhvVKRH38P8Xt3z7DmXXtjisBTRV4=,tag:j6UeYzQWx8d2+ornnfJ4sg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
