---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - appproject-edatw.yaml
  - application-edatw-cloudflared.yaml
  - application-edatw-ed8.yaml
  - application-edatw-salary-mailman.yaml
