---
# OperatorHub ClusterCatalog for OLM v1
# Provides access to community operators from operatorhub.io
# Source: quay.io/operatorhubio/catalog (upstream official catalog)
apiVersion: olm.operatorframework.io/v1
kind: ClusterCatalog
metadata:
  name: operatorhubio
spec:
  source:
    type: Image
    image:
      ref: quay.io/operatorhubio/catalog:latest
      pollIntervalMinutes: 60
