---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd-example-storage

resources:
  - namespace.yaml
  - pvc-hostpath.yaml
  - pvc-zfs.yaml
  - pvc-mayastor.yaml
  - deployment.yaml

labels:
  - pairs:
      app.kubernetes.io/name: storage-example
      app.kubernetes.io/managed-by: argocd
