# SOPS Age key secret for ArgoCD KSOPS
# This secret will be encrypted with Flux's Age key
# Flux will decrypt and deploy it to the ArgoCD namespace
# ArgoCD repo-server will use this key to decrypt application secrets
apiVersion: v1
kind: Secret
metadata:
  name: sops-age
  namespace: argocd
type: Opaque
stringData:
  keys.txt: ENC[AES256_GCM,data:WYfFDwN1XM3OC+Y4AErBHlO+GOtSERITAkCtS68BNRbScwuj4tvfq9tEAGKZ+XK4ARoKN5Gy+O0suoD/0qPaqMke8zLD9opsCnFPQWn9QyUW46bnuZo3gt2eouSvDJI2gcr3YOInUdnBnqiONyb9LqF0kTRHKah55oE6ZpURdswqlwrJ6XWtDSQnW9itBEEJuRm1sZVqQ3MB3F8K/FgrlSJS0enDwrlc/8rancBDC0v+ngf8qUJ8jh2R6YV+,iv:Tb65Av3k0fKL0Uqq373xJtr8BjeAXv7ijCJK9e8QkOU=,tag:5gbWl6vtJ6Xfh7AVODPcvg==,type:str]
sops:
  age:
    - recipient: age1nj8nwf4nc24envr8shkk8p2neqw7vr6c83h3wayyrej3drawjessu4pz98
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0OVBUd3N5SmJxd2hGQXpq
        Y3AyWlpTL0t1UHJWK3FwOTFyQytpRkdtSkU4Cm1lNU10ZmtsOXRsRmJ5U3ZYNUwx
        eEVqTWEvQVk5aFJJVTllR3o2amNrUzQKLS0tIHZsYzlrT0k5dHorZmRROWp1QVk1
        bHNKaWM1Y0dQYkwwdDUwemp0emNvZU0KMej34k7/q1tA1wJ+3f5hVE+ioANCaRKO
        XtK0vNhRHAFuul9Sc91fqDrq7d6kctM9RLX87Sjhg8S6RyYEzyYxMA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-13T17:32:14Z"
  mac: ENC[AES256_GCM,data:NpDaDBbe850MfkoQ8XF42PgFsJlm6ODEsurfc+GnRd0gB872+zDTUBObDVRL0+iV71LCHO5Egde5VNoABuDDXKGhTO3zXYo12HPOe7U/AnkjJ9QnDSlU7dtL2wN5fkJuGBvIpuSIBd8yM5Ehob5Tq2zh/DS64bM7okU9Nrd9z1A=,iv:A6bTCN151lNc4+NW/CV1kBymHOZRsYSeQQ9iCS7FXkg=,tag:xo5aRucMjLgQjJ9/jnk4CQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
