---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - helmrepository-cilium.yaml
  - helmrelease-cilium.yaml

labels:
  - pairs:
      app.kubernetes.io/name: cilium
      app.kubernetes.io/managed-by: flux
