---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# ArgoCD (Direct Helm Installation)
# GitOps continuous delivery tool for Kubernetes
# Installed via Helm using Flux CD HelmRelease

resources:
  - namespace-argocd.yaml
  - helmrepository-argo.yaml
  - helmrelease-argocd.yaml

labels:
  - pairs:
      app.kubernetes.io/name: argocd
      app.kubernetes.io/component: gitops
      app.kubernetes.io/managed-by: helm
