---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Flux Operator installed via Helm
# Manages Flux CD installations via FluxInstance CRDs
# Source: https://github.com/controlplaneio-fluxcd/flux-operator

resources:
  - namespace-flux-system.yaml
  - helmrepository-flux-operator.yaml
  - helmrelease-flux-operator.yaml

labels:
  - pairs:
      app.kubernetes.io/name: flux-operator
      app.kubernetes.io/managed-by: helm
