---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Flux Operator installed via OLM ClusterExtension
# Requires: olmv1-catalog (OperatorHub catalog)
# Version: ^0.33.0 (stable channel, automatic upgrades)

resources:
  - namespace-flux-system.yaml
  - serviceaccount-flux-operator-installer.yaml
  - clusterrole-flux-operator-installer.yaml
  - clusterrolebinding-flux-operator-installer.yaml
  - clusterextension-flux-operator.yaml

labels:
  - pairs:
      app.kubernetes.io/name: flux-operator
      app.kubernetes.io/managed-by: olm
