---
# Monitor Operator - CRD Providers
# Contains Prometheus Operator and Grafana Operator (CRD providers only)
# Exporters are in monitor-exporters, Loki is in monitor-cluster
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace-monitoring.yaml
  - helmrepository-prometheus-community.yaml
  - helmrepository-grafana.yaml
  - helmrelease-prometheus-operator.yaml
  - helmrelease-grafana-operator.yaml

labels:
  - pairs:
      app.kubernetes.io/name: monitor-operator
      app.kubernetes.io/managed-by: flux
