---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace-monitoring.yaml
  - helmrepository-prometheus-community.yaml
  - helmrepository-grafana.yaml
  - helmrelease-prometheus-operator.yaml
  - helmrelease-prometheus-node-exporter.yaml
  - helmrelease-kube-state-metrics.yaml
  - helmrelease-loki.yaml
  - helmrelease-grafana-operator.yaml

labels:
  - pairs:
      app.kubernetes.io/name: monitor-operator
      app.kubernetes.io/managed-by: flux
