---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace-monitoring.yaml
  - helmrepository-prometheus-community.yaml
  - helmrepository-grafana.yaml
  - helmrelease-kube-prometheus-stack.yaml
  - helmrelease-loki.yaml

labels:
  - pairs:
      app.kubernetes.io/name: monitor-operator
      app.kubernetes.io/managed-by: flux
