#ENC[AES256_GCM,data:NWAgC1cSAh7TPX8t2Uznb6RyufTNDHSlyuYW7Ehd4al/OUxRZ+ts2Hx4CH0Amh7WChv7wiNYcA==,iv:1yKkOdvjq1AmJ8aa9g58tZ1kVfQRV6QmN4hGRRLNIH8=,tag:t96sijmLlD2Xthw9eqyTeg==,type:comment]
#ENC[AES256_GCM,data:HKa/zEspT3JEVE9zqem7cOugcw2VE4/jM33u32DXPDxiP6siEdqok1vX19tQxnY=,iv:gG27kVZDL8TJ++4telGx6cOGjPpNxh/AOld1k8+dX3M=,tag:Q1Q9ZWTF25Xl9dfjp5DuhQ==,type:comment]
#
#ENC[AES256_GCM,data:XNKcX2ytQVN5J7oiO2hK3vEIHqWPkFEuF7X9SuRb5Hq22dw7z4jEyJ2f5GRDkGcl/kz31r508g==,iv:eVpYyqAEDIIPFAeL6cKuEmvKaLF9qwJnkcnsd/3LeNg=,tag:5ODuIrt0QXalNqrzglMKNA==,type:comment]
#ENC[AES256_GCM,data:reCTFICJ3cGHOTpyE0xrDRIkOsY9FypBLQwqo5pbywUNr7E=,iv:mdWAiXk3+BOfWMSqX3tw2WBFD5WFdoF52zxFD9w4VtE=,tag:ldLS0VQMaT04HtsIyesHQg==,type:comment]
#ENC[AES256_GCM,data:fc+7HLLvUQyByg7fe9V+sQ8TirP6ty71xNelGcElumEBuHLY4Hys+6JJsKM=,iv:Uf5CQ3+R8b2c0ywvQHY+2QsI8vvA+/pwFzjzbfxEQN4=,tag:Of60j+vGMfcxBwG4LFFVuw==,type:comment]
#ENC[AES256_GCM,data:46VKlHC9CszXi80e0jVsUH+2cTHHIBLbzViWJ5MSvAQ=,iv:sZXI22GMaPHEPyEr45FjntBFI/lzRfqjRcI5ISqrdkI=,tag:WSh6B4QshmZTZQMIkjUO3w==,type:comment]
#ENC[AES256_GCM,data:ageExrnlWWgjVoE6qo1MqnBUZfZHp1vo3R0z3svf,iv:GNJYgXWjF93qjuhz5XlpK0jqzzf7Mol0RruLa4Ym3BA=,tag:fSdRbcWaEM/WELuWfaxvjg==,type:comment]
services:
    immich-server:
        #ENC[AES256_GCM,data:jXlqgANlremCWQsTt461N1YyM0mMe5UgccqtarhQKMAotSrY,iv:pzjHN16Wv94vvKOfeAbzAiEAmcXgtjswtYUvZwItHvY=,tag:nfxlPRk145a4ftm+cHRXFQ==,type:comment]
        runtime: ENC[AES256_GCM,data:4IfP8q2u,iv:1WR+pGrq5R9TKdrxDNzuA+tFwvTZkqCeIWHzI3m6itc=,tag:6QIN5ef+5xwxMFPs9ssoqg==,type:str]
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: ENC[AES256_GCM,data:AQ9b/EN7,iv:z36tOXzhyuHeokd3mCY50cbN8JP0N2SWQZBhjlB9doo=,tag:lMJ5WN7NubNTC/+n05gUKg==,type:str]
                          count: ENC[AES256_GCM,data:EA==,iv:1N6Htl5wciBtnzaO5WKyxZ4XgvMonmvewCXQjna0k08=,tag:oBHRLqGLzOqpFqc2t3WdUg==,type:int]
                          capabilities:
                            - ENC[AES256_GCM,data:XBDR,iv:ea3pcAmxg+yLvMSAgP0B9JhmSxm07Hq+Yp19T/gUpS4=,tag:a2iQZF4eCpAoPUocTJLIJw==,type:str]
                            - ENC[AES256_GCM,data:Gtl3hGhjbA==,iv:7De2N2EIoWoI6bEldl2MsZXR+fW7Trl8/N0RTZayFVQ=,tag:P0Bl+xn651GmhLadBKZYuA==,type:str]
                            - ENC[AES256_GCM,data:a0dyClU=,iv:4LlpKXFgUrdCcm0aWMf/Q9QsrR23KDggFPYg9RPobxA=,tag:gq49lPp2awB1MUMADhD/Fg==,type:str]
        environment:
            - ENC[AES256_GCM,data:qPve2WB1X8uu0vgo9wEGT0x9BbMVZr/0yK2+c8fbUaIPCQfRc20PGaXDf2J8hVoWHUSncjFKWzDkzRIxR+k=,iv:BcJFv8ssSrt4fTK8CujAvaQdzXolzcpKrw731taW7M8=,tag:uH+DKHa91g4ajDPFK6NG1w==,type:str]
            - ENC[AES256_GCM,data:dAivqutYJBeF9CfqbY3RPu5q4oAWg0c+1/xEfD2KUzRU,iv:sSrFJf7EQc2uNLp6Z0ow5TygX07AdHpDIlUjqOlCzIk=,tag:MwKAn3DjYJhF1Qh2vkVWmg==,type:comment]
            - ENC[AES256_GCM,data:m7UOcL9Na4R662MmgGwA5KxADWqTR9tzzIX33g==,iv:X3h1bsssWW+81bWdiHBY4j4X9r6LuMVtsmRgr5YptKA=,tag:lmC9qbCmBm94NZnXe91eJg==,type:str]
            - ENC[AES256_GCM,data:gyS+BkMC82qQx+TMUhkDuljgknoj95hMnp25Pw==,iv:WBlPpS8iiIKoF2Fhyb4N2Sb0axxbbofb+Z8KR5JuFo8=,tag:dy7SdHNrW4RGomgbhhm0lA==,type:str]
        volumes:
            - ENC[AES256_GCM,data:F4eHaI11ktmn9H8fCnHHi3KPhgm83KmRKPh0Wo2y2rOclVg/gAY=,iv:f+es7e8/LfG9WyPNT5UOlNyuXeUXoEJFQP1Fui5+FvA=,tag:0caiXLx9aRoRUvkihHWi/Q==,type:comment]
            - ENC[AES256_GCM,data:UdQKOLLyJuTBAa3p9HmrsnADQEii9jLcEKz5wicooFhC/+6drFiESVKaMDggvET01g==,iv:LjlUSiuCTp1xsfLs/qNW+qwk6TAWU5edvFEwWmsVSak=,tag:S2XrQDBzrgKIV4DXKRXxPQ==,type:str]
            - ENC[AES256_GCM,data:G/JEO7evth0TqzINFRFiMskCEEsce5TE47FeYnXsJ2HnzYh+iA==,iv:Gvu2bZwRskKk+XXMBzlrdduGrBWy/4S1ldCKZGp2+CY=,tag:Te9zE41J3myzcs5Tyuf9Bg==,type:str]
            - ENC[AES256_GCM,data:Rk5Jx4VWFaLKJHxjexFjSPXYeEjh1YNRTWA90UFt89ndP04=,iv:COTE8hapROTdb4ypluU6hUgza8TKeaVde3IcfLponZM=,tag:XKR6gyNwHfaMIba5d7s8AQ==,type:str]
            - ENC[AES256_GCM,data:jJp/3IdPahcY7U88DA6wbxUf1uFXAnbWjEfSzHjMybgUfrOZYw==,iv:g2+DV+KE8NohEGG7IXn8yuIOO4GEbLV2xO63Hinq+zE=,tag:TVhimSnCjNSspY3/gjklcA==,type:str]
            - ENC[AES256_GCM,data:dMZfZ+EmtZE1iO/ccp6o7LhY6gAUabRhgVMVs/Qnici1yEEjvw==,iv:T7Y4S5ByC4RO3swDJVqc5Sdro16p/fPxLUfCK0kWIdU=,tag:Agp7XIK5xg8Tl/O4B5d+SA==,type:str]
            - ENC[AES256_GCM,data:Gwv6beXN1layj1aepEkyTlKpgQ+V6Itjs1OQGg==,iv:m2UHhxAVqZSBgC40ESMp381+Z+vnqysqS7FaAPbWM6E=,tag:Dj4K1q/ZU++h2OMsR4UJJg==,type:str]
            - ENC[AES256_GCM,data:fMGBJY6VMquBgBBD4YKrP8aL+hGg4OvL4+0UNQEPMMU=,iv:1HvJZkNKILHdWQZ82/Gl7fUw8oIkpLO8+b7r69S60/k=,tag:QUNqQUa8MwKWDFsgyyv8KA==,type:str]
        #ENC[AES256_GCM,data:kMnWJqjVwJfzeipYjGWIqVJ95ekk3zPLYsthOr4VcOHUtWdHMKZYo4DOwW7L1WkPUDtOo8Q+XpaN2Dw=,iv:F3dVMb5Vj1QkUP0SuXBRpgyEPNZYL4ZcoRGZnlJG2SQ=,tag:0NRZCFex6XZ37KbXnagjeA==,type:comment]
        ports:
            - ENC[AES256_GCM,data:Jy/koCcjEYGA,iv:UtrztqjQpgM04OrgigW2WpRh+OVnUre1jUi9i0Im//g=,tag:rNlEM755y074MPVolBVnWA==,type:str]
            - ENC[AES256_GCM,data:LrjXV9+JkaGlHqb29tIVenaDjw==,iv:wzl5n35slFfSsM6lcCMkXEWBUOrFbH1rHFYrv1y0c3Y=,tag:DgdLblLm7iFeeSDpoL1nEw==,type:comment]
            - ENC[AES256_GCM,data:52oWMei7OV4s,iv:Tti2bX8W4WVlVvpXzhFKgFMNs449IpuMTCqLlc0RJkc=,tag:6SQz+W7b2nTmto9Wkc5WLQ==,type:str]
        networks:
            immich: null
            alloy:
                ipv4_address: ENC[AES256_GCM,data:xsEi5lYZBpBoygY=,iv:ZGb8bHfnU4oFHJOT/hWdK8iG1u5GWKD8V42ULvJgxj8=,tag:oeEG+wN4nzzd8H5ry7Wk1A==,type:str]
    immich-machine-learning:
        #ENC[AES256_GCM,data:kx2wdPezTOJBHM/dgp0h+22HUsYfz0hf0cIwO/DamrSN6iVltWA=,iv:Js1ZJjJf60WLWZ18Kl0aVGxVcQJzZNo5qPYpM45QTh0=,tag:j0LXdUy0HgOBN9GEJn8iTA==,type:comment]
        image: ENC[AES256_GCM,data:TMNfhuAHXJU0/gLuBj1sPYhxOsHTiLSYfq4PdI64lWWVtUKfZs5Kkzrs9DZJXaF374SZAyI485fX9FYL4ezurMPjwWon4qGg0P4=,iv:IqLH79GWKgFYOcgP9G77qHPk7u7VwKxyg4EQ3Oe1sfg=,tag:6gsXu/OdLDpXQ1K2IVDjcQ==,type:str]
        runtime: ENC[AES256_GCM,data:loSBHlRm,iv:Dt9t0gdJHyRv2Ok21tNdbku8oj87O0VvxuO7DdtJET4=,tag:gDIjHM7EbM4Vm0V96NGJAA==,type:str]
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: ENC[AES256_GCM,data:eImvLbqs,iv:irt6TUI83nc/S8FEZeKCF6S8D87A8m4NL9Bk6vdq7VA=,tag:Vw29JcSkr0VbKOOrIhL+xg==,type:str]
                          count: ENC[AES256_GCM,data:4g==,iv:U+TQ1mTADBdzEmFUdbVj2pFCnym2W7/AJdH/C/LqYV4=,tag:Ph1k8xx+k9v3ICPvE7PgbQ==,type:int]
                          capabilities:
                            - ENC[AES256_GCM,data:VcXV,iv:CnpiGD2LSuY5gU3iAlMXl5eIYgJGGWRFk9nAIhnDBrU=,tag:9CoO3UndCuccBO0tjPRJaA==,type:str]
        environment:
            - ENC[AES256_GCM,data:S838vWk9GUYq/wKho0zaMZmuBJ1IgsfNBp8UlE6yGuRTZpUNluxRYm4ea/B2NH7DXkuXR2esOzRc/4Odj9g=,iv:+Ja5OOmDGT2eUZMKX1pS1l4EtPeih4hA8pE/0rgx5FY=,tag:BrFXdOX6y9/u5Xt42zekrg==,type:str]
    database:
        volumes:
            - ENC[AES256_GCM,data:d4u6ohZkZ51MmWqBFY3UBmYKr7grHwRQNt/YUGudUCqx/Sf1rLdTE51smSTi2MONu125g8v3ofKLfw==,iv:xjSCdXuvOfkVAyIIE3cpgP3fkqFALdPVeQj0Y/vo03A=,tag:j276XLvMUKMAj6rpRNMZ8Q==,type:str]
networks:
    alloy:
        external: ENC[AES256_GCM,data:6OMF9g==,iv:VPCSWDpcUnmDVp9ropdF39cU2+u54Yq+YJvd0rrBBbk=,tag:MrpPVzkR0MmDff9mKKqaUw==,type:bool]
        name: ENC[AES256_GCM,data:vH3P8xghWnDXvvtMKdo=,iv:i58SMHmGMOUIIO7LFnuMHccVpbm3HFsVImCeSXKtIBI=,tag:excaIr1WFnfppBmg+DqEkA==,type:str]
sops:
    age:
        - recipient: age18pns8av0m2g3wgenjnfkj046340azfytlp0jgpkw4dw7zkh83dwqlct4np
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6Vnhla3BwSzVBSWR6TnlK
            MDlGMlJwbUMxSFJpZDZ6TVQySjUweFhTL0JJCkdPMjFQM1NtT2NxektUWG5WRUdj
            a3k5TVhWR0hwWXE3SXV1NytUQlY1MXcKLS0tIEJickZsdmRyRzZMek5Kc3FKYUFI
            MDZ6aGFFVnNkR3NUNm9Jb3J3U1JhcncKIjxql6YGYeOagN/0OVvETSBHi4keShkx
            pshlkN6IveKwVFhidfG/SPSgexGDek5sZb6DUkzaAAa38Q7iqM9VHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T14:59:26Z"
    mac: ENC[AES256_GCM,data:fAYIQUtw0gXc7idQulG4zyG1+zq89KGfWWD310Nas7hTepHO5eM6P0hYi0+eITkq6RGj3lZSxFEvczpbWJ1rXt28MbpwpjQUWKOxDjHR1aLwn85cI+nnxgoGN8Ux52DP9R5am03Za5HJPkFdFjRjC1ROOaOQE1595M8zS6KWZvU=,iv:fE1hXZcP6N5Faiyki4WPS6MLclZ2jGj/y0jaHoits4A=,tag:ci50X4homH73m1mY7KiQoA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
