# SOPS age encryption key secret (ENCRYPTED)
# Managed by Terraform: kubernetes_secret.sops_age
# Only stringData section is encrypted (metadata, kind, apiVersion are plaintext)
apiVersion: v1
kind: Secret
metadata:
    name: sops-age
    namespace: flux-system
type: Opaque
stringData:
    age.agekey: ENC[AES256_GCM,data:7JlKmDGeMYQQSAacDoofwTtrZAKG47CVgo2ZOIHPA4FByS27E5yTcGLPSBcDueryqYq0BUg0ukWfZ4avMRNFmIk9BPnQYiKMILRUvLeKLZSc451IIL0b5TaVhsztmqCf3izhYxgfByBuP0npix3POzWydYSHobis4cfRoHVIc/coFf8RpTuULTcJadkWIiiy9vTxNVSCQDD9Fm2AQglkcrcloB/Y2+LIPQUPyEAak+Ws3zmBv+WldgKudWDj,iv:Rj4Ip1dwXSnikkmYB0vkRpYuCgl38o0+fPfe4cZJaMU=,tag:m6V5Qsj0BHE8B/4pzHPvMw==,type:str]
sops:
    age:
        - recipient: age169cuuq59c5dzagy3j70h7ul0q5meeqvmdc84vx4ffwg6ptxsgdvshem39p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6eG9jOGVveWlaSmZkT3BK
            Z3FLRHpwYnZ1THFLcm1XZ2JkKzhjRC9xd1NVClkwMTdrRTVOMU9kNEpxUi9EZkhH
            U3A3eFdlQ3hwYnozOFA0b3hHdUh3YjgKLS0tIHZuMUpGemcveWc1dWdWS1FZNllF
            MUdKODc2a1ArRXYza3JkSEJDSkxvaGMK3GXY3eWh1MtmDfLrKASwwypf6/yuTxs0
            ZVyupVRwr/HOR1cOB6iflD+XYxqKOOjQ0wO1AVPcer1w7F+/vQmD+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-31T12:50:05Z"
    mac: ENC[AES256_GCM,data:fUj86DoVWYleZoxyQX2qanZZuRL2nJtfNAMNnA2XKJ0fPpuNnreeGysSWmw63o0dWJ4Bg8rdVkfGHqxXr083gCQoAeKn4vThpRWgpjrNMY1WKYDnizX8LCb4mdn7c71f/8LmrtIA20IHPLnm5mI5PynJS1r2RZkDNlo2ku20W80=,iv:3fjitpTuK3k7Ny1OBeqBUDD4DsgT4vp4imV4YGcQvEs=,tag:JSIQi7H6aSwM0oWzldNv5A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
