# Flux Git credentials secret (ENCRYPTED)
# Managed by Terraform: kubernetes_secret.flux_git_credentials
# Only stringData section is encrypted (metadata, kind, apiVersion are plaintext)
apiVersion: v1
kind: Secret
metadata:
    name: flux-system
    namespace: flux-system
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:Tn6r,iv:75+GVyYWshiWfx5doMyAecdu4WoG7ok0H0+tBjhDlw0=,tag:XFL93Frab8aWjJo4ncolMQ==,type:str]
    password: ENC[AES256_GCM,data:W+tJ/Ad+M3OPEkUEfS+CsB3kzJl2Q/YRHWnuo2yHwosg6P7mNmZxlQ==,iv:lv6rbeFMhUprg9FXjiweYHtSWWx8QZPSpxPSYOxY6QM=,tag:3ojpYUdnzkL7GXcR0VM05w==,type:str]
sops:
    age:
        - recipient: age169cuuq59c5dzagy3j70h7ul0q5meeqvmdc84vx4ffwg6ptxsgdvshem39p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnSFM5K0ZWVTRCTDI3NTJu
            bzQrV1psaVorc2x5VFgzMC9PTDc0VFVGNUdBClBMdDFlVVkzOXY2NHNYRExpakNV
            dWZtSmYzSzA5bkFUMUxsb2s5a3NIcDgKLS0tIFB0RnlvTnFUSERXSVNqWXpuWWNT
            L2hlclZVdVlXSFVpeU91dmtxUzhuS0kKFUbSDZJT/UTTXgEC5NovkrJdL88oWxs2
            T9f8mmAbVexltfppHC/1oOfxfpDvUfWFpmZ/t4pWKgXYTaoVU8MW2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-31T12:51:17Z"
    mac: ENC[AES256_GCM,data:ZxwxYWaBqLex4EiNszVKKRvy0Zci0Nt7xlMWCtx7CLnBe8KtwBP7PWyi+VPPktHbxxkbOy6jZGxgVOn4YYpSq7sEqkqdPrDMnVP1B5pleL1QBm2+UmcZEzGo+gaJc/Vn3iGvbbCtkGqTE5Rb17LCQ3qqGUFqfeRgLzDrrme9+BA=,iv:Otvm1+IFSXowlc/B+nojqXj2ZFAZ0l35PKC7tejwt3k=,tag:K09VTvjx+/CHmu4IKS7LLQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
