---
# Fairwinds Helm repository
# Source for VPA and Goldilocks charts
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: fairwinds-stable
  namespace: flux-system
spec:
  interval: 24h
  url: https://charts.fairwinds.com/stable
