---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Vertical Pod Autoscaler (VPA) GitOps resources
# Recommendation-only mode (updater disabled)

resources:
  - helmrepository-fairwinds.yaml
  - helmrelease-vpa.yaml

labels:
  - pairs:
      app.kubernetes.io/name: vpa
      app.kubernetes.io/managed-by: flux
