---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace-cert-manager.yaml
  - helmrepository-cert-manager.yaml
  - helmrelease-cert-manager.yaml

labels:
  - pairs:
      app.kubernetes.io/name: cert-manager
      app.kubernetes.io/managed-by: flux
