# SOPS age encryption key secret (ENCRYPTED)
# Managed by Terraform: kubernetes_secret.sops_age
# Only stringData section is encrypted (metadata, kind, apiVersion are plaintext)
apiVersion: v1
kind: Secret
metadata:
    name: sops-age
    namespace: flux-system
type: Opaque
stringData:
    age.agekey: ENC[AES256_GCM,data:Bcz1ST9gySDC8s7iYP8P+mvSwh18cBPSVY/whDgmIBZjXj/LdAUSKXUhVTfbVZJnESmgDgHSJnSXisQgvXx2O/zXPYuG6buAzj8myq93TsfFqoFwnDdNw28TqplHd2S/mdPM8SbypItY+4fvD+VbwgnCUo4J5FDV6rTSSqjpEj5YTf0H4oAISwRZxCU+F/ZprTj8qe16BPy3n+hiLJj4vFo6VXVkmQ8kYKW0oPMpOzbcJMwMjEPRTt1CmrGT,iv:zhS54fSGdyCo1wIPQ/g6jpp7hpcnfrFcjEGWtg0Xgjg=,tag:IlGwLQSOG8QaAsvSY8HF8Q==,type:str]
sops:
    age:
        - recipient: age17rsrkd59pqkhs6kwsv052r98wrw9gc5mgd5dx6jrycdwuy23z54q2flh9w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOL05idzJwcTU2WXBUVjR0
            SXpmMzQ5TDNIcmNuL3hmTTV0OCtBTXFzMEFRCkNOK1Mwb1pTelBUYWgwTitDMElM
            UlptVFVSSlNYZi9hejR3VE03YmtJRTQKLS0tIFdPa25hek1LTjloM3J6bk9mL2Rs
            bWg1NmRkSDNrSDJnaVBUeHl1YThBNmMKA2i+VghoZN8WI0j1mUQ4jB4Fj0fWro+m
            UvsMp+xIlSkLCsA9rlsWu3xWKv8i4pW3rLBJHkwaxeTNZ9bGKtW4gg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-02T06:59:26Z"
    mac: ENC[AES256_GCM,data:1xKSs89tg5CQZNx3iOFlgI6P+neA81NXlyN7sEmuPxyuv2y6+bAdgJSVfh+O2k2EUnfAsENxVhtLD33qcctI5k+dlVAorcAZ1qzRjqmaSvYsI0NNNwLfeP6XiEK3H50QzWB0z2Gv4HAEzqnocEMEtPhs6hOe3mmBcwK0Gh4K+KU=,iv:oqr+yi8H8guIzH775htgpdc3xqd581ZwIIgA7ikZeeM=,tag:bqtayZhDIchZSbTYqXedmA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
