# Flux Git credentials secret (ENCRYPTED)
# Managed by Terraform: kubernetes_secret.flux_git_credentials
# Only stringData section is encrypted (metadata, kind, apiVersion are plaintext)
apiVersion: v1
kind: Secret
metadata:
    name: flux-system
    namespace: flux-system
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:9vEQ,iv:DQr758QcmKPJsQ+fUBjc4A6s3B6b5wD0A5G490nkC1s=,tag:Ew0DRuidC5cFP4NCqWvDTQ==,type:str]
    password: ENC[AES256_GCM,data:5dDGyz/4MHxZZfOjIakYmKXxGvKKD/I257qlIL2JCiEx2Rj6TGtf5g==,iv:YxlsRVTuPjRSIi5Tn92dlhgsODK362PSytXyeVn9aUI=,tag:4GEUPQEP0FnT9cKDdmTsVw==,type:str]
sops:
    age:
        - recipient: age17rsrkd59pqkhs6kwsv052r98wrw9gc5mgd5dx6jrycdwuy23z54q2flh9w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBNU56VVZET0NheWxyaHlh
            bFd6S1BxZ1RvdDVYTjJzc2pHRHdMZ3RkTEdZCml3bXU0bXhWVHo5cnhqK1B5RmFp
            OTF0Ky9pWC9SekRJNFhjaWtlYWJ3OHMKLS0tIFJlbktxY0EwcHFjeStOSEZWemNH
            RVJ6MVc2d1NTNHFHaitGeEdCY3NNcEUKS8zw7cAgh5EZam8Bg6lUuCItuz664BXW
            zaHMX0qWNv/Mcikp8ou/AucIT4QAMQJbwon/veyHLWmFA6+fMwEwYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-02T07:07:21Z"
    mac: ENC[AES256_GCM,data:yOrHC/V9yLlPbzqMlotjum7UWdJosgZS2S6kb/MX2CWfzz6n4ztJ85P7PXo6SlMKLYDBjeyzSYnhM6wIKMbF+/OO3tHT0PyPeSHDhX198l60AaBZOGNV7x+8y1H5L77enR9hk3ZFkZzkFYoLMcVI/BaqUgNuk7olyeatpJkWZkw=,iv:h6fsZnF2+50GRQIzofFWlc5VCk0mKFE/GakPvNFwSTQ=,tag:zWBjwRSLJssUAqBck0qu7g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
