---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - helmrepository-csi-driver-smb.yaml
  - helmrelease-csi-driver-smb.yaml

labels:
  - pairs:
      app.kubernetes.io/name: csi-driver-smb
      app.kubernetes.io/managed-by: flux
