# SOPS configuration for alloy secrets
# Domain: docker | Environment: alloy-shangkuei-xyz-unraid
# Generated: 2026-01-20T21:02:47+08:00

creation_rules:
  # Encrypted environment file (.enc.env)
  - path_regex: \.enc\.env$
    age: age18pns8av0m2g3wgenjnfkj046340azfytlp0jgpkw4dw7zkh83dwqlct4np

  # Encrypted docker compose override files (*.enc.yml)
  - path_regex: \.enc\.yml$
    age: age18pns8av0m2g3wgenjnfkj046340azfytlp0jgpkw4dw7zkh83dwqlct4np
