---
# Prometheus self-monitoring ServiceMonitor
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/instance: cluster
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/managed-by: kustomize
    prometheus.io/scrape-by: alloy
  name: prometheus
  namespace: monitoring
spec:
  endpoints:
    - metricRelabelings:
        - action: drop
          regex: prometheus_http_.*_bucket
          sourceLabels:
            - __name__
      path: /metrics
      port: http-web
      relabelings:
        - action: replace
          replacement: shangkuei-lab
          targetLabel: cluster
    - metricRelabelings:
        - action: drop
          regex: prometheus_http_.*_bucket
          sourceLabels:
            - __name__
      path: /metrics
      port: reloader-web
      relabelings:
        - action: replace
          replacement: shangkuei-lab
          targetLabel: cluster
  namespaceSelector:
    matchNames:
      - monitoring
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus
