# SOPS Age key secret for ArgoCD KSOPS
# This secret will be encrypted with Flux's Age key
# Flux will decrypt and deploy it to the ArgoCD namespace
# ArgoCD repo-server will use this key to decrypt application secrets
apiVersion: v1
kind: Secret
metadata:
    name: sops-age
    namespace: argocd
type: Opaque
stringData:
    keys.txt: ENC[AES256_GCM,data:bOUfk8gcT7Vs5fQS6FHsiJORRznklz5AIXFkEdL26jGrH1tiByvAnc0IxG+0v0wYb1BeZ1Y26FydbEBa4TZIFBX5Sso1VRI8siQZVuEw8evSkToRaxmOhInCQI52RZbq1BUTnnfPmULqdHo0snEebLY1xAWobP482JJzI10J2hN/XCo3yQeg0etAHZ1pHuq2mEWnQwF+JMX3YfBWkGN0VUabvdtO984SEHqFrGX0KjEg8o8bAOyb/vXysFiN,iv:jTQXRkP4hsFo3ow3PUhYmbrBNGCo9xnqCR214g5Gz4Y=,tag:Z5XtUkCZtAzSLXcLQTasXQ==,type:str]
sops:
    age:
        - recipient: age17rsrkd59pqkhs6kwsv052r98wrw9gc5mgd5dx6jrycdwuy23z54q2flh9w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2Tm82RndaMERkbEx0dnFo
            Y2NlUCtTOWdQOE1aQTk3bGFKSGJ0anpMZUhrCm1wUnZva0M3cTgxYXlla3k4emxQ
            UUhMZTVxeksvR1ltc21KUU5IVC9UblEKLS0tIGU2MVVXVWdJUHM0R3Q2NDFRYXJ4
            OVk0UW45RC9MMXlFU05pcjNnWGxDL2sK8Mnfiw7hZWlGbWrKxMDkeGLi1fFAJtJp
            nVZPIwkPGsBXygtk623SPNOXn2PhO9Zp5vNfs6Rjfr4kjKY4toXXxQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-02T11:56:59Z"
    mac: ENC[AES256_GCM,data:uazWt9+0B59MnF/jJhfxXzkkG4Dc9PK6ic7jzMQT84kAJ3wBudRqKE5SO+Cz5nY72FQNjGZ56zm6ABJIH1W9+cpRUihU6/UUU4agF25oPFXfxsPlAv4Y+q8H2vTfgIZoxYqZXTJir9C8wBrLET9nIIdS8H+OJbIxiv7I4Bm25hM=,iv:b6KZCH7Zl5NX0euQZZPDtwmBO/Mk0l0TY5KRJEE9eSg=,tag:e3hDd3KCs2VryatLqr5bAQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
