---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace-seaweedfs.yaml
  - helmrepository-seaweedfs-operator.yaml
  - helmrelease-seaweedfs-operator.yaml
  # Additional RBAC for monitoring (required when metricsPort is configured)
  - clusterrole-seaweedfs-operator-monitoring.yaml
  - clusterrolebinding-seaweedfs-operator-monitoring.yaml

labels:
  - pairs:
      app.kubernetes.io/name: seaweedfs-operator
      app.kubernetes.io/managed-by: flux
