---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd-example-app1

resources:
  - namespace.yaml
  - deployment.yaml
  - configmap.yaml
  - service.yaml

labels:
  - pairs:
      app.kubernetes.io/name: test-app1
      app.kubernetes.io/managed-by: argocd
