# ArgoCD SOPS Age key secret (to be encrypted)
# This secret is deployed to argocd namespace for KSOPS decryption
apiVersion: v1
kind: Secret
metadata:
    name: sops-age
    namespace: argocd
type: Opaque
stringData:
    keys.txt: ENC[AES256_GCM,data:kpBpzJf7KPKehPSon3b+I01TKCpswHUZ7R63MNjJfJ0xpio43GHX8hqLGgav06DfQBMM81qEOIO0UJAlQyLMZTF8/6bFKVMuzsej7GmRZvKzw9iFKkdZG7COyjIinTVYArUIsfCGWuo08MA9dtkaGZ91OoxLaJ2dIirmVBS3B2WLkrMYFIZGqAqMWkYXP39BcuwVjjuMno/6kmZ/VxpZoAe9EmRzVd1s0OV4AbbfnT6/I6zErp/EYbDKDpv1,iv:FWyMjyi9AMfwKycDHD01fsPrwt75ZhUbvqZ96lzg3Pg=,tag:MZvuxcRaL+HAAcEd/wgxXw==,type:str]
sops:
    age:
        - recipient: age1xd9vrcj6n5nazq3tek8t89qxaky5eg9339phyddeemu99hqgvfcqkr2ysp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtLzAwb2NzWmJ1aytLcE5Q
            aDl0OUZZaDZjQ29qeFUxWUs2RWVXYlZjM1N3CmUrM0EzOGZML2JqK3FPVmM0STFD
            Uit4VlNWYzhRZGNoNHRDSXNoYnR4bkkKLS0tIEZjMThUckFSMnlraG95NExLRm56
            SkFtSCsvak9uS3QwT2plczhqUXI4aGsKDv1HFqFBfPVVrXYdkAtqfQXb+ieyx64Q
            WaZuE0ionxkwE6kJR+ye61gC+/Sa9RO2GYXhyFxtlNUNZ6CA/ntDRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-15T03:47:02Z"
    mac: ENC[AES256_GCM,data:WCn/Mw3a8bUrB13KVJHUg6athGmlpdx8VGIWpfWZl8+Jh9GgMMJRpAy6WiOL1MFQU3JnouwTiEDAJx9nkovHM9AikZAiarrtMdmUmzrx/hRoU5u9YF15dqjpujpiaYZ31nrInXRx9u2AdtKOvo+L13Z+3l2KTndJKGshyhTyCLU=,iv:IncTGXuYK+N9AzGZCo3uoHwRbcDeodMm1INqM54YpQw=,tag:0YYdVxH6wjG/foSx6YXWWA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
